@startuml
' title: Music Library
' package: http://fake-audio.org/music-lib
' version: 1.1
' description: This information model defines a library of audio tracks, organized by album, with associated metadata regarding each track. It is modeled on the types of library data maintained by common websites and music file tag editors.
' license: CC0-1.0
' exports: ['Library']

' !theme spacelab
hide empty members
hide circle

class "Library" as n0 <<MapOf>>
class "Album" as n2 <<Record>>
  n2 : 1 artist : Artist
  n2 : 2 title : String
  n2 : 3 pub_data : Publication-Data
  n2 : 4 tracks : Track [1..*]
  n2 : 5 total_tracks : Integer{1..*}
  n2 : 6 cover_art : Image [0..1]
class "Publication-Data" as n3 <<Record>>
  n3 : 1 publisher : String
  n3 : 2 release_date : String /date
class "Image" as n4 <<Record>>
  n4 : 1 image_format : Image-Format
  n4 : 2 image_content : Binary
class "Artist" as n6 <<Record>>
  n6 : 1 artist_name : String
  n6 : 2 instruments : Instrument unique [1..*]
class "Track" as n8 <<Record>>
  n8 : 1 location : File-Path
  n8 : 2 metadata : TrackInfo
class "TrackInfo" as n9 <<Record>>
  n9 : 1 t_number : Number
  n9 : 2 title : String
  n9 : 3 length : Integer{1..*}
  n9 : 4 audio_format : Audio-Format
  n9 : 5 featured_artist : Artist unique [0..*]
  n9 : 6 track_art : Image [0..1]
  n9 : 7 genre : Genre
  n2 "1 "--> "1" n6 : artist
  n2 "1 "--> "1" n3 : pub_data
  n2 "1 "--> "1..*" n8 : tracks
  n2 "1 "--> "0..1" n4 : cover_art
  n8 "1 "--> "1" n9 : metadata
  n9 "1 "--> "0..*" n6 : featured_artist
  n9 "1 "--> "0..1" n4 : track_art
@enduml